Buyhood/BuyHood

- src/main/java/api/buyhood/domain/product/entity/Category.java
- src/main/java/api/buyhood/domain/product/repository/CategoryRepository.java
- 상품 도메인 내 카테고리 엔티티 및 리포지토리 생성
- `Category` 및 `CategoryRepository` 생성
- `Product` 클래스 내 카테고리 필드 타입 수정 후 연관관계 매핑
| Category | ![image](https://github.com/user-attachments/assets/278af431-41c0-42ee-869b-a8f55a310d6d) |
| CategoryRepository | ![image](https://github.com/user-attachments/assets/874f4e2b-4622-4e95-90e9-e550d8d0ee03) |
| Product | ![image](https://github.com/user-attachments/assets/fd1ccffd-b25d-478e-9f70-7497258eb345) |
> feat: Creating Category entity and repository

- src/main/java/api/buyhood/global/common/dto/CustomExceptionDto.java
- src/main/java/api/buyhood/global/common/exception/enums/CartErrorCode.java
- src/main/java/api/buyhood/global/common/exception/enums/CategoryErrorCode.java
- src/main/java/api/buyhood/global/common/exception/enums/CommonErrorCode.java
- src/main/java/api/buyhood/global/common/exception/enums/ErrorCode.java
- src/main/java/api/buyhood/global/common/exception/enums/OrderErrorCode.java
- src/main/java/api/buyhood/global/common/exception/enums/ProductErrorCode.java
- src/main/java/api/buyhood/global/common/exception/enums/SellerErrorCode.java
- src/main/java/api/buyhood/global/common/exception/enums/StoreErrorCode.java
- src/main/java/api/buyhood/global/common/exception/enums/UserErrorCode.java
- src/main/java/api/buyhood/global/common/handler/GlobalExceptionHandler.java
- `InvalidRequestException` 핸들러 구현
- `InvalidRequestException` 핸들러 구현
- `CustomExceptionDto`로 내부 필드 고정
| 예외 발생 시 | ![image](https://github.com/user-attachments/assets/8d6ce30a-8ddf-4edc-b790-1ddd8505dad4) |
| 전역 예외 처리 핸들러 및 에러 코드 필드 수정 후 | ![스크린샷 2025-05-27 112512](https://github.com/user-attachments/assets/94a00a6e-238d-4d6b-ac3e-9746ba9af12a) |
- detail 필드를 사용할 것인지 아니면 다른 필드로 바꾸거나 아예 제거할 것인지 정해야 함
> feat: Implementing the InvalidException exception handling handler

- src/main/java/api/buyhood/global/common/entity/BaseTimeEntity.java
- BaseTimeEntity에 markDeleted() 메서드 추가
- 새로운 API 추가 (예: `/users`)
- 기존 로직 리팩토링 (예: `UserService`)
- 테스트 코드 추가
| 메서드 추가 |![image](https://github.com/user-attachments/assets/73056e3e-cd28-4183-aa14-bde8e79d87bf) |
> refactor: Add markDeleted()

- src/main/java/api/buyhood/domain/product/controller/CategoryController.java
- src/main/java/api/buyhood/domain/product/dto/response/GetCategoryRes.java
- src/main/java/api/buyhood/domain/product/dto/response/PageCategoryRes.java
- src/main/java/api/buyhood/domain/product/entity/Category.java
- src/main/java/api/buyhood/domain/product/repository/CategoryRepository.java
- src/main/java/api/buyhood/domain/product/service/CategoryService.java
- src/main/java/api/buyhood/global/common/exception/enums/CategoryErrorCode.java
- 카테고리 조회 API 구현
- MFLP-14
- 카테고리 단건 조회
- 카테고리 전체 조회
- 카테고리 depth 별 조회
| 단건 조회 | ![image](https://github.com/user-attachments/assets/522b25b6-6eab-46e8-bc80-053cd08986f6) |
| 전체 조회 | ![스크린샷 2025-05-27 202129](https://github.com/user-attachments/assets/38141717-4d15-47b4-bdff-60bbf7920238) |
| depth 별 조회 | ![스크린샷 2025-05-27 220451](https://github.com/user-attachments/assets/e82f7851-fd9c-40f0-a41e-d2c5bed1faf2) |
> feat(MFLP-14): Implementing the category get method

- build.gradle
- src/main/java/api/buyhood/domain/auth/controller/AuthController.java
- src/main/java/api/buyhood/domain/auth/dto/req/SignInUserReq.java
- src/main/java/api/buyhood/domain/auth/dto/req/SigninUserReq.java
- src/main/java/api/buyhood/domain/auth/dto/res/SignInUserRes.java
- src/main/java/api/buyhood/domain/auth/service/AuthService.java
- src/main/java/api/buyhood/domain/user/repository/UserRepository.java
- src/main/java/api/buyhood/global/common/exception/enums/AuthErrorCode.java
- 로그인 기능 구현했습니다
MFLP-28
- 로그인
| 로그인 성공| ![로그인 성공](https://github.com/user-attachments/assets/7b251dc7-6cf3-4e95-8291-4c188000be29) |
| 로그인 실패| ![없는회원으로 로그인시 실패](https://github.com/user-attachments/assets/ada9d519-efee-4b07-af5f-86d8c57daa14) |
그동안 테스트를 하려고 security를 비활성화했다면 더이상 그러지않아도 됩니다! ㅎㅎ
> feat(MFLP-28): Implementing Login

- src/main/java/api/buyhood/domain/cart/controller/CartController.java
- src/main/java/api/buyhood/domain/cart/repository/CartRepository.java
- src/main/java/api/buyhood/domain/cart/service/CartService.java
- src/main/java/api/buyhood/global/common/exception/enums/CartErrorCode.java
- src/main/java/api/buyhood/global/common/exception/enums/CommonErrorCode.java
- 장바구니 조회 기능 구현
- 장바구니 조회 api 추가 (/api/v1/carts)
| 장바구니 조회 | ![image](https://github.com/user-attachments/assets/0d2b5d11-58f4-4719-9d10-7fc8418326c4) |
> feat(MFLP-12): Developing View Cart

- src/main/java/api/buyhood/domain/cart/controller/CartController.java
- src/main/java/api/buyhood/domain/cart/dto/response/CartRes.java
- src/main/java/api/buyhood/domain/cart/repository/CartRepository.java
- src/main/java/api/buyhood/domain/cart/service/CartService.java
- src/main/java/api/buyhood/global/common/exception/enums/CartErrorCode.java
- src/main/java/api/buyhood/global/common/exception/enums/CommonErrorCode.java
- 장바구니 비우기 기능 추가 
- 장바구니 비우기 api 추가 
| 장바구니 삭제 전 redis | ![image](https://github.com/user-attachments/assets/4d204a08-9db2-4857-8f7b-c944a9422900) |
| 장바구니 삭제 요청| ![image](https://github.com/user-attachments/assets/5b0b51c5-4abb-402a-8764-dda4ea5f5828)|
|장바구니 삭제 후 redis| ![image](https://github.com/user-attachments/assets/d02bb583-8ebb-4d1a-95df-1b12abbe6183)|
|예외처리| ![image](https://github.com/user-attachments/assets/20a33bed-f0fa-4df0-b068-fc658b6855ed)|
> feat(MFLP-13): Developing Clear Cart

- src/main/java/api/buyhood/domain/product/controller/ProductController.java
- src/main/java/api/buyhood/domain/product/dto/request/RegisteringProductReq.java
- src/main/java/api/buyhood/domain/product/dto/response/RegisteringProductRes.java
- src/main/java/api/buyhood/domain/product/service/ProductService.java
- 상품 등록 API 구현
- MFLP-29
- 상품 등록 API 구현
| 상품 등록 | ![스크린샷 2025-05-28 181715](https://github.com/user-attachments/assets/ac17ebd2-d34e-459a-aea2-9f57312f96a2) |
| 카테고리 없이 상품 등록 | ![스크린샷 2025-05-28 181746](https://github.com/user-attachments/assets/2b566d68-74fc-40aa-9d66-3b7b385cd3e9) |
| 상품 등록 중 카테고리 번호를 입력했으나 찾을 수 없을 경우 | ![스크린샷 2025-05-28 181800](https://github.com/user-attachments/assets/6110ab61-afb7-4dda-8133-6f2dbc0bfdb4) |
> feat(MFLP-29): Implementing the Product Registration API

- src/main/java/api/buyhood/domain/product/controller/ProductController.java
- src/main/java/api/buyhood/domain/product/dto/response/GetProductRes.java
- src/main/java/api/buyhood/domain/product/dto/response/PageProductRes.java
- src/main/java/api/buyhood/domain/product/repository/ProductRepository.java
- src/main/java/api/buyhood/domain/product/service/ProductService.java
- src/main/java/api/buyhood/global/common/exception/enums/ProductErrorCode.java
- 상품 조회 API 구현
- MFLP-29
- 상품 단건 조회
- 상품 전체 조회
- 상품 키워드 조회
| 상품 단건 조회 | ![스크린샷 2025-05-28 230146](https://github.com/user-attachments/assets/aa5809c2-ebc6-4667-837a-c30e13b50aff) |
| 상품을 찾을 수 없음 | ![스크린샷 2025-05-28 230252](https://github.com/user-attachments/assets/65ee4747-c761-467c-b45d-2159d7172243) |
| 상품 전체 조회 | ![스크린샷 2025-05-28 230200](https://github.com/user-attachments/assets/851e4159-b705-4e3e-9335-de68c65f45e9) |
| 상품 키워드 조회 (키워드 미입력) | ![스크린샷 2025-05-28 230209](https://github.com/user-attachments/assets/51df13f7-7527-457f-8c66-64aa0ce3b184) |
| 상품 키워드 조회 (키워드 입력) | ![스크린샷 2025-05-28 230234](https://github.com/user-attachments/assets/c853e21b-4a6e-404c-8574-5b3d756675d2) |
- 어떤 조회가 필요할 지 어떤 방식으로 정렬할 …
> feat(MFLP-29): Implementing the Product Get API

- src/main/java/api/buyhood/domain/product/controller/ProductController.java
- src/main/java/api/buyhood/domain/product/service/ProductService.java
- 상품 삭제 API 구현
- MFLP-33
- 상품 삭제 API 구현
| 상품 삭제 | ![스크린샷 2025-05-29 161735](https://github.com/user-attachments/assets/ec2f07cf-dcd5-4ea1-b28f-6402cc689e0a) |
| 상품 삭제 결과 | ![스크린샷 2025-05-29 161746](https://github.com/user-attachments/assets/d28380ed-3f3e-469f-9360-f72780f03867) |
> feat(MFLP-33): Implement the product delete API

- src/main/java/api/buyhood/domain/auth/controller/AuthController.java
- src/main/java/api/buyhood/domain/auth/dto/req/SignupSellerReq.java
- src/main/java/api/buyhood/domain/auth/dto/res/SignupSellerRes.java
- src/main/java/api/buyhood/domain/auth/service/AuthService.java
- src/main/java/api/buyhood/domain/seller/entity/Seller.java
- src/main/java/api/buyhood/domain/seller/repository/SellerRepository.java
- 사업자 회원가입 구현했습니다
MFLP-34
- 사업자 회원가입 구현
- 에러코드 USER와 몇개 겹쳐서 수정
| 회원가입 성공 | ![회원가입성공](https://github.com/user-attachments/assets/fa55a3fb-2a67-4062-914e-174f8200df42) |
리뷰해주시면 다음 꺼 기다리고있습니다 ㅎㅎ
> feat(MFLP-34) : Implement SellerSignUp

- src/main/java/api/buyhood/domain/order/controller/OrderController.java
- src/main/java/api/buyhood/domain/order/controller/OrderHIsttoryController.java
- src/main/java/api/buyhood/domain/order/dto/response/OrderHistoryRes.java
- src/main/java/api/buyhood/domain/order/entity/OrderHistory.java
- src/main/java/api/buyhood/domain/order/repository/OrderHistoryRepository.java
- src/main/java/api/buyhood/domain/order/service/OrderHistoryService.java
- src/main/java/api/buyhood/global/common/exception/enums/OrderErrorCode.java
- 주문 단건 조회 (주문 아이디로 조회)
- 주문 다건 조회( 로그인한 유저의 주문 내역)
- 주문 다건 조회(seller용 자신의 store의 모든 주문 내역 조회)
- 주문 다건 조회(관리자용: 모든 주문 내역 조회)
- 주문 단건 조회 (주문 아이디로 조회)
- 주문 다건 조회( 로그인한 유저의 주문 내역)
- 주문 다건 조회(seller용 자신의 store의 모든 주문 내역 조회)
- 주문 다건 조회(관리자용: 모든 주문 내역 조회)
- 기존 로직 리팩토링 (예: `UserService`)
- 테스트 코드 추가
| 주문 단건 조회|![image](https://github.com/user-attachments/assets/07f5a3db-f5a1-4c99-abeb-94cbeb5faa58)|
| 주문 단건 조회 실패|![image](https://github.com/user-attachments/assets/c874ef00-3d17-4eac-bea5-5e5b39f2deb3)|
| 주문 다건 조회 (본인)| ![image](https://github.com/user-attachments/assets/53e50fc5-e3f1-4da1-8729-f36532e99015)|
| 주문 다건 조회 (seller)| …
> feat(MFLP-26): Developing Get Order

- src/main/java/api/buyhood/domain/store/controller/StoreController.java
- src/main/java/api/buyhood/domain/store/dto/response/GetStoreRes.java
- src/main/java/api/buyhood/domain/store/dto/response/PageStoreRes.java
- src/main/java/api/buyhood/domain/store/repository/StoreRepository.java
- src/main/java/api/buyhood/domain/store/service/StoreService.java
- 가게 조회 API 구현
- MFLP-40
- 가게 단건 조회
- 가게 전체 조회
- 가게 키워드 조회 (가게 이름)
| 가게 단건 조회 | ![스크린샷 2025-05-30 010335](https://github.com/user-attachments/assets/ab2f7b31-af16-447e-91ba-3ac6e8fd27e3) |
| 가게를 찾을 수 없음 | ![스크린샷 2025-05-30 010554](https://github.com/user-attachments/assets/37cc3007-0411-43d9-9be9-59c94484711b) |
| 가게 전체 조회 | ![스크린샷 2025-05-30 010417](https://github.com/user-attachments/assets/855addaa-2ec3-4815-8ce7-bc030801d753) |
| 가게 키워드 조회 | ![스크린샷 2025-05-30 010442](https://github.com/user-attachments/assets/cc9d0582-7ed6-4f20-bf8c-e35af0130d67) |
| 가게 키워드 조회(키워드에 맞는 결과 없음) | ![스크린샷 2025-05-30 010452](https://github.com/user-attachments/assets/6476ea9a-4605-46fd-abc7-ed042251bf68) |
리뷰어가 알아야 할 중요한 사항이나 …
> feat(MFLP-40): Implement the store get API

- src/main/java/api/buyhood/domain/auth/controller/AuthController.java
- src/main/java/api/buyhood/domain/auth/dto/req/SignInSellerReq.java
- src/main/java/api/buyhood/domain/auth/dto/res/SignInSellerRes.java
- src/main/java/api/buyhood/domain/auth/service/AuthService.java
- src/main/java/api/buyhood/domain/seller/repository/SellerRepository.java
- src/main/java/api/buyhood/domain/user/service/UserService.java
- src/main/java/api/buyhood/global/common/exception/enums/AuthErrorCode.java
- src/main/java/api/buyhood/global/common/exception/enums/SellerErrorCode.java
- src/main/java/api/buyhood/global/common/exception/enums/UserErrorCode.java
- 사업자 로그인 기능구현했습니다.
MFLP-38
- sellersignin 구현
- endpoint 수정
- errorcode 수정
- 로그인 시 비밀번호 검증 누락 버그 픽스
| 셀러 로그인 성공 | ![셀러 로그인성공](https://github.com/user-attachments/assets/14e57121-b3dd-4af5-b239-a6a93c77a004) |
> feat(MFLP-38) : Implement SellerSignIn

- src/main/java/api/buyhood/domain/cart/controller/CartController.java
- src/main/java/api/buyhood/domain/cart/dto/request/CartReq.java
- src/main/java/api/buyhood/domain/cart/dto/request/CreateCartReq.java
- src/main/java/api/buyhood/domain/cart/dto/response/CartItemRes.java
- src/main/java/api/buyhood/domain/cart/dto/response/CartRes.java
- src/main/java/api/buyhood/domain/cart/entity/Cart.java
- src/main/java/api/buyhood/domain/cart/entity/CartItem.java
- src/main/java/api/buyhood/domain/cart/repository/CartRepository.java
- src/main/java/api/buyhood/domain/cart/service/CartService.java
- src/main/java/api/buyhood/domain/order/dto/response/OrderHistoryRes.java
- src/main/java/api/buyhood/domain/order/entity/OrderHistory.java
- src/main/java/api/buyhood/domain/order/service/OrderHistoryService.java
- 주문 카트 도메인에 Authentication 추가
- 불필요한 메서드 정리 및 response 리팩토링
MFLP-44
- 기존 로직 리팩토링 (예: `UserService`)
| 주문성공 | ![주문성공](https://github.com/user-attachments/assets/d670e00e-2f13-4418-9383-572309c90a8d) |
> refactor(MFLP-44): refactoring unnecessary method and adding Authentication on Cart & Order

- src/main/java/api/buyhood/domain/store/controller/StoreController.java
- src/main/java/api/buyhood/domain/store/dto/request/PatchStoreReq.java
- src/main/java/api/buyhood/domain/store/entity/Store.java
- src/main/java/api/buyhood/domain/store/service/StoreService.java
- src/main/java/api/buyhood/global/common/exception/enums/StoreErrorCode.java
- 가게 수정 API 구현
- MFLP-41
- 가게 수정 API 구현
| 가게 수정 1 | ![스크린샷 2025-05-30 112320](https://github.com/user-attachments/assets/0b114051-37d0-4b91-bb92-4ec54253d772) |
| 가게 수정 2 | ![스크린샷 2025-05-30 112320](https://github.com/user-attachments/assets/d5795501-ca5a-4078-a5e4-ee71bb7c29bd) |
| 가게 수정 결과 | ![스크린샷 2025-05-30 112315](https://github.com/user-attachments/assets/299f9f6c-dfb0-4f8d-a1af-d0d7d9b10744) |
| 가게 수정 시 사업자를 찾을 수 없음 | ![스크린샷 2025-05-30 112449](https://github.com/user-attachments/assets/dadf1e4f-b0fe-4929-8762-2a59315c16fb) |
| 동일한 가게 이름 실패 | ![스크린샷 2025-05-30 112501](https://github.com/user-attachments/assets/6c250bfa-15fd-47a9-ba85-3af9dbb27f51) |
PR 작성자가 확인해야 할 …
> feat(MFLP-41): Implementing the store modification API

- src/main/java/api/buyhood/domain/product/controller/ProductController.java
- src/main/java/api/buyhood/domain/product/repository/CategoryProductRepository.java
- src/main/java/api/buyhood/domain/product/repository/ProductRepository.java
- src/main/java/api/buyhood/domain/product/service/ProductService.java
- 상품 도메인 리팩토링
- MFLP-47
- 상품 논리적 삭제 구현
- 조회 시 삭제되지 않은 상품만 나오도록 구현
- 사업자만 사용할 수 있도록 `@Secured` 사용
| 미리 만들어 놓은 상품 | ![image](https://github.com/user-attachments/assets/47971467-4a48-46e4-98d9-58afe596f922) |
| 1번 상품 삭제 | ![image](https://github.com/user-attachments/assets/26a64c95-f550-4f91-ba86-43be42a87925) |
| 1번 상품 삭제 결과 | ![image](https://github.com/user-attachments/assets/e50e93a5-0efe-4258-a3e8-175e14c42a4d) |
| 상품 수정 실패 (삭제된 상품 조회) | ![image](https://github.com/user-attachments/assets/07fdafee-204f-4d07-ae92-bb081b940a0a) |
| 상품 삭제 시 중간 테이블 결과 | ![image](https://github.com/user-attachments/assets/7f3fc5ea-ada6-452e-9075-79955835c53a) |
- seller 로그인이 필요합니다.
> refactor(MFLP-47): Product domain refactoring

- src/main/java/api/buyhood/domain/product/entity/ProductCategory.java
- src/main/java/api/buyhood/domain/product/repository/ProductCategoryRepository.java
- src/main/java/api/buyhood/domain/product/service/CategoryService.java
- src/main/java/api/buyhood/domain/product/service/ProductService.java
- 클래스명 변경
- MFLP-51
- `CategoryProduct` -> `ProductCategory`
| PNG | ![스크린샷](사진을 넣어주세요) |
- 직접적인 로직 변경은 없고 단순히 클래스명 변경으로 인한 수정만 있습니다.
- 변경한 이유는 `상품-카테고리`가 더 자연스러운 것 같아 변경했습니다. 
> refactor(MFLP-51): Rename a class

- src/main/java/api/buyhood/domain/product/controller/ProductController.java
- ProductController에 `@Secured` 추가
- MFLP-56
- 모든 상품 API는 SELLER만 호출할 수 있도록 변경
| 일반 사용자 회원가입 | ![image](https://github.com/user-attachments/assets/537230f5-5099-4b76-95d2-ec35a6a51096) |
| 일반 사용자 상품 전체 조회 실패 | ![image](https://github.com/user-attachments/assets/595ab247-e3c4-4b48-929d-c03c1e30870c) |
> fix(MFLP-56): Add `@Secured` to ProductController

- src/main/java/api/buyhood/domain/order/controller/OrderHistoryController.java
- src/main/java/api/buyhood/domain/order/dto/response/GetOrderRes.java
- src/main/java/api/buyhood/domain/order/repository/OrderHistoryRepository.java
- src/main/java/api/buyhood/domain/order/service/OrderHistoryService.java
- Seller용 주문 조회 수정 (seller 검증 로직 추가)
- 주문 다건 조회 url 마지막 부분에 /all 추가
- OrderHistoryService의 getOrdersBySeller 부분의 seller 검증 로직 추가
- OrderHistoryController의 url부분 수정
| 주문 다건 조회(seller용)|![image](https://github.com/user-attachments/assets/bddf5034-955c-475a-bbab-bbaeefd3626a) |
| 주문 다건 조회(seller용) 예외 처리 |![image](https://github.com/user-attachments/assets/b2141e1b-463e-4794-80d6-fa20628ee141) |
> refactor(MFLP-57): Refactor Get Order
